//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamirhaneMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MusteriArac
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public short MusteriID { get; set; }

        [DisplayName("Müþteri Adý")]
        public string MusteriAd { get; set; }

        [DisplayName("Müþteri Soyadý")]
        public string MusteriSoyad { get; set; }

        [DisplayName("Telefon")]
        public string MusteriTel { get; set; }

        [DisplayName("Marka")]
        public string AracMarka { get; set; }

        [DisplayName("Model")]
        public short AracModel { get; set; }

        [DisplayName("Plaka")]
        public string AracPlaka { get; set; }

        [DisplayName("Baþlangýç Tarihi")]
        public System.DateTime AracGirisTarih { get; set; }

        [DisplayName("Bitiþ Tarihi")]
        public System.DateTime AracBitisTarih { get; set; }

        [DisplayName("Deðiþen Parça")]
        public string DegisenParca { get; set; }

        [DisplayName("Toplam Ücret")]
        public string ToplamUcret { get; set; }

        [DisplayName("Açýklama")]
        public string Aciklama { get; set; }
    }
}
